@startuml

actor "User" as user
node "Pernikahan RESTful API" {
    component "Controller" as controller
    component "Sevices" as service
    component "Repository" as repository
}

database "PostgreSQL" as database

user <--> controller
controller <--> service
service <--> repository
repository <--> database

@enduml